relay-server/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::domain('localhost')->group(function () {
     Route::view('/', 'index');
     Route::view('/mock', 'mock.index');
// });

//*************************************************************************************************************************
// システムオーナー向け
//*************************************************************************************************************************
Route::namespace('So')->name('so.')->prefix('so')->group(function () {

    //ログイン認証関連
    Auth::routes([
        'register' => false,
        'verify'   => false
    ]);

    //ログイン認証後
    Route::middleware(['auth:guard_system_owner', 'permission:system_owner_permission','check.session.timeout'])->group(function () {
        //============
        // 画面
        //============
        //ダッシュボード画面
        Route::get('/', 'DashboardController@index')->name('dashboard');
        //業者一覧画面
        Route::get('/vendor', 'VendorController@index')->name('vendor.index');
        //管理会社一覧画面
        Route::get('/managementCompany', 'ManagementCompanyController@index')->name('managementCompany.index');

        //============
        // その他
        //============
        //業者登録処理
        Route::post('/vendor', 'VendorController@store')->name('vendor.store');
        //業者更新処理
        Route::put('/vendor/{vendorId}', 'VendorController@update')->name('vendor.update');
        //管理会社登録処理
        Route::post('/managementCompany', 'ManagementCompanyController@store')->name('managementCompany.store');
        //管理会社更新処理
        Route::put('/managementCompany/{managementCompanyId}', 'ManagementCompanyController@update')->name('managementCompany.update');
    });
});


//*************************************************************************************************************************
// 業者向け
//*************************************************************************************************************************
Route::namespace('Vn')->name('vn.')->prefix('vn')->group(function () {

    //ログイン認証関連
    Auth::routes([
        'register' => false,
        'reset'    => false,
        'verify'   => false
    ]);

    //ログイン認証後
    Route::middleware(['auth:guard_vendor_manager', 'permission:vendor_manager_permission','check.session.timeout'])->group(function () {
        //============
        // 画面
        //============
        //ダッシュボード画面
        Route::get('/', 'DashboardController@index')->name('dashboard');
        //作業員管理画面
        Route::get('/vendorMember', 'VendorMemberController@index')->name('vendorMember.index');
        //問合せ入札履歴画面
        Route::get('/bidHistory', 'RequestController@getBidHistory')->name('bidHistory');
        //入札可能問合せ一覧画面
        Route::get('/bidPossible', 'RequestController@getBidPossible')->name('bidPossible');
        //完了報告一覧画面
        Route::get('/report', 'ReportController@getReportList')->name('reportList');
        //完了報告書詳細画面
        Route::get('/report/{report_id}', 'ReportController@getReportDetail')->name('reportDetail');
        //完了報告書編集画面
        Route::get('/report/{report_id}/edit', 'ReportController@getReportEdit')->name('reportEdit');
        //完了報告書プレビュー画面
        Route::post('/report/{report_id}/preview', 'ReportController@getReportPreview')->name('reportPreview');
        //マイページ
        Route::get('/mypage', 'MyPageController@index')->name('mypage');

        //============
        // その他
        //============
        //作業員登録処理
        Route::post('/vendorMember', 'VendorMemberController@store')->name('vendorMember.store');
        //作業員更新処理
        Route::put('/vendorMember/{user_id}', 'VendorMemberController@update')->name('vendorMember.update');
        //完了報告書更新処理
        Route::put('/report/{report_id}', 'ReportController@updateReport')->name('updateReport');
        //完了報告書提出処理
        Route::post('/report/{report_id}', 'ReportController@submitReport')->name('submitReport');
        //完了報告書PDFダウンロード処理
        Route::post('/report/{report_id}/pdf', 'ReportController@downloadReportPdf')->name('downloadReportPdf');
        //マイページ・更新処理
        Route::post('/mypage/update', 'MyPageController@update')->name('mypage.update');
        //問合せ担当者変更処理
        Route::post('/request/{request_id}/changeRequestHandler', 'RequestController@changeRequestHandler')->name('changeRequestHandler');
    });
});


//*************************************************************************************************************************
// 管理会社向け
//*************************************************************************************************************************
Route::namespace('Mc')->name('mc.')->prefix('mc')->group(function () {

    //ログイン認証関連
    Auth::routes([
        'register' => false,
        'reset'    => false,
        'verify'   => false
    ]);

    //ログイン認証後
    Route::middleware(['auth:guard_management_company_member', 'permission:management_company_member_permission','check.session.timeout'])->group(function () {
        //============
        // 画面
        //============
        //ダッシュボード画面
        Route::get('/', 'DashboardController@index')->name('dashboard');
        //問合せ一覧画面
        Route::get('/request', 'RequestController@index')->name('request');
        //問合せ一覧画面(ID指定)
        Route::get('/request/{request_id}/once', 'RequestController@index')->name('request.once');
        //ユーザー管理画面
        Route::get('/managementCompanyMember', 'ManagementCompanyMemberController@index')->name('managementCompanyMember');
        //完了報告一覧画面
        Route::get('/report', 'ReportController@getReportList')->name('reportList');
        //完了報告一覧画面
        Route::get('/report/{report_id}/once', 'ReportController@getReportList')->name('reportList.once');
        //完了報告書詳細画面
        Route::get('/report/{report_id}', 'ReportController@getReportDetail')->name('reportDetail');
        //入居者一覧画面
        Route::get('/resident', 'ResidentController@getResidentList')->name('residentList');

        //============
        // その他
        //============
        //AccessKeyファイルダウンロード処理
        Route::post('/getAccessKey', 'AccessKeyController@getAccessKey')->name('getAccessKey');
        //ユーザー登録処理
        Route::post('/managementCompanyMember', 'ManagementCompanyMemberController@store')->name('managementCompanyMember.store');
        //ユーザー更新処理
        Route::put('/managementCompanyMember/{user_id}', 'ManagementCompanyMemberController@update')->name('managementCompanyMember.update');
        //問合せ履歴 エクスポート
        Route::post('/request/export', 'RequestController@exportRequestCsv')->name('request.export');
        //完了報告書 承認処理
        Route::post('/report/{report_id}/approve', 'ReportController@approveReport')->name('approveReport');
        //完了報告書 差し戻し処理
        Route::post('/report/{report_id}/decline', 'ReportController@declineReport')->name('declineReport');
        //完了報告書PDFダウンロード処理
        Route::post('/report/{report_id}/pdf', 'ReportController@downloadReportPdf')->name('downloadReportPdf');
        //完了報告書ZIPファイルダウンロード処理
        Route::post('/report/{report_id}/zip', 'ReportController@downloadReportZip')->name('downloadReportZip');
    });
});


// パスワードリセット関連
Route::prefix('password_reset')->name('password_reset.')->group(function () {
    Route::prefix('email')->name('email.')->group(function () {
        // パスワードリセットメール送信フォームページ
        Route::get('/', 'Api\ForgotPasswordController@emailFormResetPassword')->name('form');
        // メール送信処理
        Route::post('/', 'Api\ForgotPasswordController@sendEmailResetPassword')->name('send');
        // メール送信完了ページ
        Route::get('/send_complete', 'Api\ForgotPasswordController@sendComplete')->name('send_complete');
    });
    // パスワード再設定ページ
    Route::get('/edit', 'Api\ForgotPasswordController@edit')->name('edit');
    // パスワード更新処理
    Route::post('/update', 'Api\ForgotPasswordController@update')->name('update');
    // パスワード更新終了ページ
    Route::get('/edited', 'Api\ForgotPasswordController@edited')->name('edited');
});


//*************************************************************************************************************************
// その他
//*************************************************************************************************************************
Route::name('other.')->group(function () {
    //============
    // 画面
    //============
    //本登録画面
    Route::get('/account/register', 'Mc\AccountController@index')->name('account');
    //本登録処理
    Route::post('/account/register', 'Mc\AccountController@register')->name('account.register');
});

relay-server/app/Http/Controllers/Vn/DashboardController.php
<?php

namespace App\Http\Controllers\Vn;

use App\Library\Cmn;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $webRequest)
    {
        $vendorId = $webRequest->session()->get('vendor_id');

        //管理会社別対応件数
        $chartByMc =
        \App\Models\Request::
        select(
            'mc.name',
            'r.management_company_id',
            \DB::raw('COUNT(*) as cnt'),
        )
        ->from('requests as r')
        ->join('management_companies as mc', function ($join) {
            $join->on('mc.management_company_id', 'r.management_company_id');
        })
        ->join('request_handle_users as rhu', function ($join) use ($vendorId) {
            $join->on('rhu.request_id', 'r.request_id')
            ->where('rhu.group_id', $vendorId);
        })
        ->groupBy([
            'mc.name',
            'r.management_company_id',
        ])
        ->get();

        //時間別問合せ数
        $selectChartByTimeZone =
        \App\Models\Request::
        select(
            \DB::raw('HOUR(r.created_at) as hour'),
            \DB::raw('COUNT(*) as cnt'),
        )
        ->from('requests as r')
        ->join('request_handle_users as rhu', function ($join) use ($vendorId) {
            $join->on('rhu.request_id', 'r.request_id')
            ->where('rhu.group_id', $vendorId);
        })
        ->groupBy('hour')
        ->get();
        $chartByTimeZone = array();
        for ($i = 0; $i < 24; $i++) {
            foreach ($selectChartByTimeZone as $cbtz) {
                if ($i == $cbtz->hour) {
                    array_push($chartByTimeZone, $cbtz->cnt);
                }
            }
            if (count($chartByTimeZone) === $i) {
                array_push($chartByTimeZone, 0);
            }
        }

        return view('vn.dashboard', [
            'chartByTimeZone' => $chartByTimeZone,
            'chartByMc' => $chartByMc,
        ]);
    }
}

relay-server/app/Http/Controllers/Vn/MyPageController.php
<?php

namespace App\Http\Controllers\Vn;

use App\Library\Cmn;
use App\Mail\CreateAccountVendorMemberNotification;
use App\Models\User;
use App\Models\Vendor;
use App\Models\VendorMember;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreVendor;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Http\Request;

class MyPageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $vendorId = $request->session()->get('vendor_id');
        $vendor = \App\Models\Vendor::find($vendorId);
        return view('vn/mypage', ['vendor' => $vendor]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //バリデーション
        $validatedData = $request->validate([
            'work_areas' => 'nullable',
            'work_time_from' => 'nullable|date_format:H:i',
            'work_time_to' => 'nullable|date_format:H:i',
            'work_weeks' => 'nullable',
            'work_items' => 'nullable',
        ]);

        try {
            DB::transaction(function () use ($request) {
                //変数
                $vendorId = $request->session()->get('vendor_id');
                $workAreas = $request->work_areas;
                $workTimeFrom = $request->work_time_from;
                $workTimeTo = $request->work_time_to;
                $workWeeks = $request->work_weeks;
                $workItems = $request->work_items;

                //更新
                $vendor = \App\Models\Vendor::find($vendorId);
                $vendor->work_areas = $workAreas;
                $vendor->work_time_from = $workTimeFrom;
                $vendor->work_time_to = $workTimeTo;
                $vendor->work_weeks = $workWeeks;
                $vendor->work_items = $workItems;
                $vendor->save();
            });

        } catch (\Exception $e) {
            \Log::error("システム例外が発生しました。".$e->getMessage());
            return redirect()->back()->withInput()->withErrors("システム例外が発生しました。".$e->getMessage());
        }

        return redirect(url()->previous())->with('my_status', '更新が完了しました。');
    }
}

relay-server/resources/views/vn/dashboard.blade.php
@extends('layouts.vn.app')

@section('content')
<div class="container-fluid mt-5">
    <div class="row justify-content-center">
        <div class="col-md-4 mb-4">
            <div class="col-md-12 dashboard-content">
                <h6>管理会社別対応件数</h6>
                <canvas id="chart-by-mc"></canvas>
            </div>
        </div>
        <div class="col-md-4 mb-4">
            <div class="col-md-12 dashboard-content">
                <h6>時間帯別問合せ数</h6>
                <canvas id="chart-by-time-zone"></canvas>
            </div>
        </div>
    </div>
</div>
<script>
var timeLabels = new Array();
for (i = 0; i < 24; i++) {
    timeLabels.push(i + '時');
}


var cbmc = document.getElementById("chart-by-mc").getContext('2d');
var chartByMc = new Chart(cbmc, {
    type: 'bar',
    data: {
        labels: [
            @foreach ($chartByMc as $cbmc)
                '{{ $cbmc->name }}',
            @endforeach
        ],
        datasets: [{
            label: '対応数',
            data: [
                @foreach ($chartByMc as $cbmc)
                    {{ $cbmc->cnt.',' }}
                @endforeach
            ],
            backgroundColor: 'rgba(101, 137, 229, 0.5)',
            borderColor: 'rgba(101, 137, 229, 1)',
            borderWidth: 1
        }]
    },
    options: {
        legend: {
            display: false
        },
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true,
                    userCallback: function(label, index, labels) {
                        // when the floored value is the same as the value we have a whole number
                        if (Math.floor(label) === label) {
                            return label;
                        }
                    },
                },
            }],
            xAxes: [{
                gridLines: {
                    display: false
                },
            }]
        }
    }
});

var cbtz = document.getElementById("chart-by-time-zone").getContext('2d');
var chartByTimeZone = new Chart(cbtz, {
    type: 'bar',
    data: {
        labels: timeLabels,
        datasets: [{
            label: '問合せ数',
            data: [
                @foreach ($chartByTimeZone as $val)
                    {{ $val.',' }}
                @endforeach
            ],
            backgroundColor: 'rgba(101, 137, 229, 0.5)',
            borderColor: 'rgba(101, 137, 229, 1)',
            borderWidth: 1
        }]
    },
    options: {
        legend: {
            display: false
        },
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true,
                    userCallback: function(label, index, labels) {
                        // when the floored value is the same as the value we have a whole number
                        if (Math.floor(label) === label) {
                            return label;
                        }
                    },
                },
            }],
            xAxes: [{
                gridLines: {
                    display: false
                },
            }]
        }
    }
});
</script>
@endsection

relay-server/resources/views/vn/mypage.blade.php
@extends('layouts.vn.app')

@section('content')
<ul class="nav nav-tabs pl-4"></ul>
<div class="container-fluid px-5 mt-n3">
    <form method="POST" action="{{ route('vn.mypage.update') }}" onsubmit="buttonDisabled();">
        @csrf
        <div class="row justify-content-center mt-4">
            <div class="col-md-12 mt-3">
                <label for="work_area" style="color: #464f69;">対応エリア</label>
                <div class="col-md-6 mypage-work-items">
                    @php
                        $work_areas = ['朝倉郡筑前町','朝倉郡東峰村','朝倉市','飯塚市','糸島市','うきは市','大川市','大野城市','大牟田市','小郡市','遠賀郡芦屋町','遠賀郡岡垣町','遠賀郡遠賀町','遠賀郡水巻町','春日市','糟屋郡宇美町','糟屋郡粕屋町','糟屋郡篠栗町','糟屋郡志免町','糟屋郡新宮町','糟屋郡須惠町','糟屋郡久山町','嘉穂郡桂川町','嘉麻市','北九州市小倉北区','北九州市小倉南区','北九州市戸畑区','北九州市門司区','北九州市八幡西区','北九州市八幡東区','北九州市若松区','鞍手郡鞍手町','鞍手郡小竹町','久留米市','古賀市','田川郡赤村','田川郡糸田町','田川郡大任町','田川郡川崎町','田川郡香春町','田川郡添田町','田川郡福智町','田川市','太宰府市','筑後市','筑紫野市','築上郡上毛町','築上郡築上町','築上郡吉富町','那珂川市','中間市','直方市','福岡市早良区','福岡市城南区','福岡市中央区','福岡市西区','福岡市博多区','福岡市東区','福岡市南区','福津市','豊前市','三井郡大刀洗町','三潴郡大木町','京都郡苅田町','京都郡みやこ町','みやま市','宮若市','宗像市','柳川市','八女郡広川町','八女市','行橋市',];
                        $areas = array();
                        if (old('work_areas')) {
                            $areas = old('work_areas');
                        } else {
                            $areas = $vendor->work_areas;
                        }
                    @endphp
                    @foreach ($work_areas as $idx => $area)
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="work_area_{{$idx}}" name="work_areas[]" value="{{$area}}" @if(in_array($area, $areas, true)) checked @endif>
                            <label class="form-check-label" for="work_area_{{$idx}}">{{$area}}</label>
                        </div>
                    @endforeach
                    @error('work_areas')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
            <div class="col-md-12 mt-3">
                <label for="work_time_from" style="color: #464f69;">対応可能曜日</label>
                <div class="col-md-6 mypage-work-items">
                    @php
                        $work_weeks = ['日', '月', '火', '水', '木', '金', '土'];
                        $weeks = array();
                        if (old('work_weeks')) {
                            $weeks = old('work_weeks');
                        } else {
                            $weeks = $vendor->work_weeks;
                        }
                    @endphp
                    @foreach ($work_weeks as $idx => $week)
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="work_week_{{$idx}}" name="work_weeks[]" value="{{$week}}" @if(in_array($week, $weeks, true)) checked @endif>
                            <label class="form-check-label" for="work_week_{{$idx}}">{{$week}}</label>
                        </div>
                    @endforeach
                    @error('work_weeks')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
            <div class="col-md-12 mt-3">
                <label for="work_time_from" style="color: #464f69;">対応可能時間</label>
                <div class="col-md-6 pl-0">
                    <input type="time" class="form-control d-inline-block @error('work_time_from') is-invalid @enderror" name="work_time_from" id="work_time_from" style="width:150px;" value="{{old('work_time_from', substr($vendor->work_time_from, 0, 5))}}">
                    <span class="d-inline-block">～</span>
                    <input type="time" class="form-control d-inline-block @error('work_time_to') is-invalid @enderror" name="work_time_to" id="work_time_to" style="width:150px;" value="{{old('work_time_to', substr($vendor->work_time_to, 0, 5))}}">
                    @error('work_time_from')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    @error('work_time_to')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
            <div class="col-md-12 mt-3">
                <label style="color: #464f69;">対応可能項目</label>
                <div class="col-md-6 mypage-work-items">
                    @php
                        $work_items = ['エアコン','水廻り','ガス廻り','各種設備','スイッチ／コンセント','感知器（熱／煙）','クロス','床','ガラス','サッシ','畳／襖','網戸','建具','換気扇','照明','鍵','物干','解体','大工／造作','木工','軽鉄／金物','電気','通信','左官','給排水','空調','美装','インターホン','自動扉（オートロック含む）','機械警備','郵便受','宅配ボックス','掲示板','エレベーター','立体駐車場','駐輪場','テレビアンテナ','インターネット','電話','監視カメラ','水廻り（貯水槽／直結増圧ポンプ）','ガス廻り（都市ガス／ＬＰガス）','電気（低圧／高圧）','消防設備（消火器／防火扉／火災受信機／スプリンクラー／誘導灯）','植栽','照明（共用灯／非常灯）','巡回清掃（日常／定期（機械洗浄含む）／特別（高圧洗浄含む）・・ゴミ庫／廃棄問題含む）','雑排水管','汚水管','雨樋（雨水管含む）','防水','塗装','タイル','サイン','外部足場','外壁診断',];
                        $items = array();
                        if (old('work_items')) {
                            $items = old('work_items');
                        } else {
                            $items = $vendor->work_items;
                        }
                    @endphp
                    @foreach ($work_items as $idx => $item)
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="work_item_{{$idx}}" name="work_items[]" value="{{$item}}" @if(in_array($item, $items, true)) checked @endif>
                            <label class="form-check-label" for="work_item_{{$idx}}">{{$item}}</label>
                        </div>
                    @endforeach
                    @error('work_items')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
            <div class="col-md-12 mt-4">
                <button type="submit" class="btn btn-search" style="width:110px;">保存</button>
            </div>
        </div>
    </form>
</div>

<script>
</script>

@endsection