relay-server/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::domain('localhost')->group(function () {
     Route::view('/', 'index');
     Route::view('/mock', 'mock.index');
// });

//*************************************************************************************************************************
// システムオーナー向け
//*************************************************************************************************************************
Route::namespace('So')->name('so.')->prefix('so')->group(function () {

    //ログイン認証関連
    Auth::routes([
        'register' => false,
        'verify'   => false
    ]);

    //ログイン認証後
    Route::middleware(['auth:guard_system_owner', 'permission:system_owner_permission','check.session.timeout'])->group(function () {
        //============
        // 画面
        //============
        //ダッシュボード画面
        Route::get('/', 'DashboardController@index')->name('dashboard');
        //業者一覧画面
        Route::get('/vendor', 'VendorController@index')->name('vendor.index');
        //管理会社一覧画面
        Route::get('/managementCompany', 'ManagementCompanyController@index')->name('managementCompany.index');

        //============
        // その他
        //============
        //業者登録処理
        Route::post('/vendor', 'VendorController@store')->name('vendor.store');
        //業者更新処理
        Route::put('/vendor/{vendorId}', 'VendorController@update')->name('vendor.update');
        //管理会社登録処理
        Route::post('/managementCompany', 'ManagementCompanyController@store')->name('managementCompany.store');
        //管理会社更新処理
        Route::put('/managementCompany/{managementCompanyId}', 'ManagementCompanyController@update')->name('managementCompany.update');
    });
});


//*************************************************************************************************************************
// 業者向け
//*************************************************************************************************************************
Route::namespace('Vn')->name('vn.')->prefix('vn')->group(function () {

    //ログイン認証関連
    Auth::routes([
        'register' => false,
        'reset'    => false,
        'verify'   => false
    ]);

    //ログイン認証後
    Route::middleware(['auth:guard_vendor_manager', 'permission:vendor_manager_permission','check.session.timeout'])->group(function () {
        //============
        // 画面
        //============
        //ダッシュボード画面
        Route::get('/', 'DashboardController@index')->name('dashboard');
        //作業員管理画面
        Route::get('/vendorMember', 'VendorMemberController@index')->name('vendorMember.index');
        //問合せ入札履歴画面
        Route::get('/bidHistory', 'RequestController@getBidHistory')->name('bidHistory');
        //入札可能問合せ一覧画面
        Route::get('/bidPossible', 'RequestController@getBidPossible')->name('bidPossible');
        //完了報告一覧画面
        Route::get('/report', 'ReportController@getReportList')->name('reportList');
        //完了報告書詳細画面
        Route::get('/report/{report_id}', 'ReportController@getReportDetail')->name('reportDetail');
        //完了報告書編集画面
        Route::get('/report/{report_id}/edit', 'ReportController@getReportEdit')->name('reportEdit');
        //完了報告書プレビュー画面
        Route::post('/report/{report_id}/preview', 'ReportController@getReportPreview')->name('reportPreview');
        //マイページ
        Route::get('/mypage', 'MyPageController@index')->name('mypage');

        //============
        // その他
        //============
        //作業員登録処理
        Route::post('/vendorMember', 'VendorMemberController@store')->name('vendorMember.store');
        //作業員更新処理
        Route::put('/vendorMember/{user_id}', 'VendorMemberController@update')->name('vendorMember.update');
        //完了報告書更新処理
        Route::put('/report/{report_id}', 'ReportController@updateReport')->name('updateReport');
        //完了報告書提出処理
        Route::post('/report/{report_id}', 'ReportController@submitReport')->name('submitReport');
        //完了報告書PDFダウンロード処理
        Route::post('/report/{report_id}/pdf', 'ReportController@downloadReportPdf')->name('downloadReportPdf');
        //マイページ・更新処理
        Route::post('/mypage/update', 'MyPageController@update')->name('mypage.update');
        //問合せ担当者変更処理
        Route::post('/request/{request_id}/changeRequestHandler', 'RequestController@changeRequestHandler')->name('changeRequestHandler');
    });
});


//*************************************************************************************************************************
// 管理会社向け
//*************************************************************************************************************************
Route::namespace('Mc')->name('mc.')->prefix('mc')->group(function () {

    //ログイン認証関連
    Auth::routes([
        'register' => false,
        'reset'    => false,
        'verify'   => false
    ]);

    //ログイン認証後
    Route::middleware(['auth:guard_management_company_member', 'permission:management_company_member_permission','check.session.timeout'])->group(function () {
        //============
        // 画面
        //============
        //ダッシュボード画面
        Route::get('/', 'DashboardController@index')->name('dashboard');
        //問合せ一覧画面
        Route::get('/request', 'RequestController@index')->name('request');
        //問合せ一覧画面(ID指定)
        Route::get('/request/{request_id}/once', 'RequestController@index')->name('request.once');
        //ユーザー管理画面
        Route::get('/managementCompanyMember', 'ManagementCompanyMemberController@index')->name('managementCompanyMember');
        //完了報告一覧画面
        Route::get('/report', 'ReportController@getReportList')->name('reportList');
        //完了報告一覧画面
        Route::get('/report/{report_id}/once', 'ReportController@getReportList')->name('reportList.once');
        //完了報告書詳細画面
        Route::get('/report/{report_id}', 'ReportController@getReportDetail')->name('reportDetail');
        //入居者一覧画面
        Route::get('/resident', 'ResidentController@getResidentList')->name('residentList');

        //============
        // その他
        //============
        //AccessKeyファイルダウンロード処理
        Route::post('/getAccessKey', 'AccessKeyController@getAccessKey')->name('getAccessKey');
        //ユーザー登録処理
        Route::post('/managementCompanyMember', 'ManagementCompanyMemberController@store')->name('managementCompanyMember.store');
        //ユーザー更新処理
        Route::put('/managementCompanyMember/{user_id}', 'ManagementCompanyMemberController@update')->name('managementCompanyMember.update');
        //問合せ履歴 エクスポート
        Route::post('/request/export', 'RequestController@exportRequestCsv')->name('request.export');
        //完了報告書 承認処理
        Route::post('/report/{report_id}/approve', 'ReportController@approveReport')->name('approveReport');
        //完了報告書 差し戻し処理
        Route::post('/report/{report_id}/decline', 'ReportController@declineReport')->name('declineReport');
        //完了報告書PDFダウンロード処理
        Route::post('/report/{report_id}/pdf', 'ReportController@downloadReportPdf')->name('downloadReportPdf');
        //完了報告書ZIPファイルダウンロード処理
        Route::post('/report/{report_id}/zip', 'ReportController@downloadReportZip')->name('downloadReportZip');
    });
});


// パスワードリセット関連
Route::prefix('password_reset')->name('password_reset.')->group(function () {
    Route::prefix('email')->name('email.')->group(function () {
        // パスワードリセットメール送信フォームページ
        Route::get('/', 'Api\ForgotPasswordController@emailFormResetPassword')->name('form');
        // メール送信処理
        Route::post('/', 'Api\ForgotPasswordController@sendEmailResetPassword')->name('send');
        // メール送信完了ページ
        Route::get('/send_complete', 'Api\ForgotPasswordController@sendComplete')->name('send_complete');
    });
    // パスワード再設定ページ
    Route::get('/edit', 'Api\ForgotPasswordController@edit')->name('edit');
    // パスワード更新処理
    Route::post('/update', 'Api\ForgotPasswordController@update')->name('update');
    // パスワード更新終了ページ
    Route::get('/edited', 'Api\ForgotPasswordController@edited')->name('edited');
});


//*************************************************************************************************************************
// その他
//*************************************************************************************************************************
Route::name('other.')->group(function () {
    //============
    // 画面
    //============
    //本登録画面
    Route::get('/account/register', 'Mc\AccountController@index')->name('account');
    //本登録処理
    Route::post('/account/register', 'Mc\AccountController@register')->name('account.register');
});

relay-server/app/Http/Controllers/Vn/DashboardController.php
<?php

namespace App\Http\Controllers\Vn;

use App\Library\Cmn;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $webRequest)
    {
        $vendorId = $webRequest->session()->get('vendor_id');

        //管理会社別対応件数
        $chartByMc =
        \App\Models\Request::
        select(
            'mc.name',
            'r.management_company_id',
            \DB::raw('COUNT(*) as cnt'),
        )
        ->from('requests as r')
        ->join('management_companies as mc', function ($join) {
            $join->on('mc.management_company_id', 'r.management_company_id');
        })
        ->join('request_handle_users as rhu', function ($join) use ($vendorId) {
            $join->on('rhu.request_id', 'r.request_id')
            ->where('rhu.group_id', $vendorId);
        })
        ->groupBy([
            'mc.name',
            'r.management_company_id',
        ])
        ->get();

        //時間別問合せ数
        $selectChartByTimeZone =
        \App\Models\Request::
        select(
            \DB::raw('HOUR(r.created_at) as hour'),
            \DB::raw('COUNT(*) as cnt'),
        )
        ->from('requests as r')
        ->join('request_handle_users as rhu', function ($join) use ($vendorId) {
            $join->on('rhu.request_id', 'r.request_id')
            ->where('rhu.group_id', $vendorId);
        })
        ->groupBy('hour')
        ->get();
        $chartByTimeZone = array();
        for ($i = 0; $i < 24; $i++) {
            foreach ($selectChartByTimeZone as $cbtz) {
                if ($i == $cbtz->hour) {
                    array_push($chartByTimeZone, $cbtz->cnt);
                }
            }
            if (count($chartByTimeZone) === $i) {
                array_push($chartByTimeZone, 0);
            }
        }

        return view('vn.dashboard', [
            'chartByTimeZone' => $chartByTimeZone,
            'chartByMc' => $chartByMc,
        ]);
    }
}

relay-server/app/Http/Controllers/Vn/MyPageController.php
<?php

namespace App\Http\Controllers\Vn;

use App\Library\Cmn;
use App\Mail\CreateAccountVendorMemberNotification;
use App\Models\User;
use App\Models\Vendor;
use App\Models\VendorMember;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreVendor;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Http\Request;

class MyPageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $vendorId = $request->session()->get('vendor_id');
        $vendor = \App\Models\Vendor::find($vendorId);
        return view('vn/mypage', ['vendor' => $vendor]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //バリデーション
        $validatedData = $request->validate([
            'work_areas' => 'nullable',
            'work_time_from' => 'nullable|date_format:H:i',
            'work_time_to' => 'nullable|date_format:H:i',
            'work_weeks' => 'nullable',
            'work_items' => 'nullable',
        ]);

        try {
            DB::transaction(function () use ($request) {
                //変数
                $vendorId = $request->session()->get('vendor_id');
                $workAreas = $request->work_areas;
                $workTimeFrom = $request->work_time_from;
                $workTimeTo = $request->work_time_to;
                $workWeeks = $request->work_weeks;
                $workItems = $request->work_items;

                //更新
                $vendor = \App\Models\Vendor::find($vendorId);
                $vendor->work_areas = $workAreas;
                $vendor->work_time_from = $workTimeFrom;
                $vendor->work_time_to = $workTimeTo;
                $vendor->work_weeks = $workWeeks;
                $vendor->work_items = $workItems;
                $vendor->save();
            });

        } catch (\Exception $e) {
            \Log::error("システム例外が発生しました。".$e->getMessage());
            return redirect()->back()->withInput()->withErrors("システム例外が発生しました。".$e->getMessage());
        }

        return redirect(url()->previous())->with('my_status', '更新が完了しました。');
    }
}

relay-server/resources/views/layouts/vn/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Title -->
    <title>Coco-en for Vendor</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    <script src="{{ asset('js/jquery-3.5.1.min.js').'?'.date('YmdHis') }}" ></script>
    <script src="{{ asset('js/bootstrap.min.js').'?'.date('YmdHis') }}" ></script>
    <script src="{{ asset('js/common.js').'?'.date('YmdHis') }}" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <script src="{{ asset('js/chartjs-plugin-colorschemes.js').'?'.date('YmdHis') }}" ></script>

    <!-- Styles -->
    <link href="{{ asset('css/bootstrap.min.css').'?'.date('YmdHis') }}" rel="stylesheet">
    <link href="{{ asset('css/common.css').'?'.date('YmdHis') }}" rel="stylesheet">
</style>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      @unless (Auth::guard('guard_vendor_manager')->check())
        <main role="main" class="col-md-12 ml-sm-auto">
        @if (session('info'))
          <div class="container-fluid mt-5">
            <div class="row justify-content-center">
              <div class="alert alert-warning col-md-12">
                {{ session('info') }}
              </div>
            </div>
          </div>
          @endif
          @yield('content')
        </main>
      @else
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse">
          <div class="sidebar-sticky pt-3">
            <div id="sidebarLogo">
              <img src="{{ asset('img/logo-coco-en.svg') }}">
              <div id="sidebarTitle">業者向け</div>
            </div>
            <ul class="nav flex-column">
              <li class="nav-item @if('/'.request()->path() === route('vn.dashboard', [], false)) nav-item-active @endif">
                <a class="nav-link" href="{{ route('vn.dashboard') }}">
                  ダッシュボード
                </a>
              </li>
              <li class="nav-item @if('/'.request()->path() === route('vn.mypage', [], false)) nav-item-active @endif">
                <a class="nav-link" href="{{ route('vn.mypage') }}">
                  マイページ
                </a>
              </li>
              <li class="nav-item @if('/'.request()->path() === route('vn.vendorMember.index', [], false)) nav-item-active @endif">
                <a class="nav-link" href="{{ route('vn.vendorMember.index') }}">
                  作業員管理
                </a>
              </li>
              <li class="nav-item @if('/'.request()->path() === route('vn.bidHistory', [], false)) nav-item-active @endif">
                <a class="nav-link" href="{{ route('vn.bidHistory') }}">
                  問合せ入札履歴
                </a>
              </li>
              <li class="nav-item @if('/'.request()->path() === route('vn.bidPossible', [], false)) nav-item-active @endif">
                <a class="nav-link" href="{{ route('vn.bidPossible') }}">
                  入札可能問合せ一覧
                </a>
              </li>
              <li class="nav-item @if('/'.request()->path() === route('vn.reportList', [], false)) nav-item-active @endif">
                <a class="nav-link" href="{{ route('vn.reportList') }}">
                  完了報告一覧
                </a>
              </li>
            </ul>
            <ul class="nav flex-column logout pb-4">
              <li class="nav-item">
                <a class="nav-link" href="{{ route('vn.logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                      ログアウト
                  </a>
                  <form id="logout-form" action="{{ route('vn.logout') }}" method="POST" style="display: none;">
                      @csrf
                  </form>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4" style="padding:0 !important;">
          <!-- フラッシュメッセージ -->
          @if (session('my_status'))
          <div class="container-fluid mt-5">
            <div class="row justify-content-center">
              <div class="alert alert-success col-md-12">
                {{ session('my_status') }}
              </div>
            </div>
          </div>
          @endif
          @if (session('info'))
          <div class="container-fluid mt-5">
            <div class="row justify-content-center">
              <div class="alert alert-warning col-md-12">
                {{ session('info') }}
              </div>
            </div>
          </div>
          @endif
          @yield('content')
        </main>
      @endunless
    </div>
  </div>
</body>
</html>