relay-server/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::domain('localhost')->group(function () {
     Route::view('/', 'index');
     Route::view('/mock', 'mock.index');
// });

//*************************************************************************************************************************
// システムオーナー向け
//*************************************************************************************************************************
Route::namespace('So')->name('so.')->prefix('so')->group(function () {

    //ログイン認証関連
    Auth::routes([
        'register' => false,
        'verify'   => false
    ]);

    //ログイン認証後
    Route::middleware(['auth:guard_system_owner', 'permission:system_owner_permission','check.session.timeout'])->group(function () {
        //============
        // 画面
        //============
        //ダッシュボード画面
        Route::get('/', 'DashboardController@index')->name('dashboard');
        //業者一覧画面
        Route::get('/vendor', 'VendorController@index')->name('vendor.index');
        //管理会社一覧画面
        Route::get('/managementCompany', 'ManagementCompanyController@index')->name('managementCompany.index');

        //============
        // その他
        //============
        //業者登録処理
        Route::post('/vendor', 'VendorController@store')->name('vendor.store');
        //業者更新処理
        Route::put('/vendor/{vendorId}', 'VendorController@update')->name('vendor.update');
        //管理会社登録処理
        Route::post('/managementCompany', 'ManagementCompanyController@store')->name('managementCompany.store');
        //管理会社更新処理
        Route::put('/managementCompany/{managementCompanyId}', 'ManagementCompanyController@update')->name('managementCompany.update');
    });
});


//*************************************************************************************************************************
// 業者向け
//*************************************************************************************************************************
Route::namespace('Vn')->name('vn.')->prefix('vn')->group(function () {

    //ログイン認証関連
    Auth::routes([
        'register' => false,
        'reset'    => false,
        'verify'   => false
    ]);

    //ログイン認証後
    Route::middleware(['auth:guard_vendor_manager', 'permission:vendor_manager_permission','check.session.timeout'])->group(function () {
        //============
        // 画面
        //============
        //ダッシュボード画面
        Route::get('/', 'DashboardController@index')->name('dashboard');
        //作業員管理画面
        Route::get('/vendorMember', 'VendorMemberController@index')->name('vendorMember.index');
        //問合せ入札履歴画面
        Route::get('/bidHistory', 'RequestController@getBidHistory')->name('bidHistory');
        //入札可能問合せ一覧画面
        Route::get('/bidPossible', 'RequestController@getBidPossible')->name('bidPossible');
        //完了報告一覧画面
        Route::get('/report', 'ReportController@getReportList')->name('reportList');
        //完了報告書詳細画面
        Route::get('/report/{report_id}', 'ReportController@getReportDetail')->name('reportDetail');
        //完了報告書編集画面
        Route::get('/report/{report_id}/edit', 'ReportController@getReportEdit')->name('reportEdit');
        //完了報告書プレビュー画面
        Route::post('/report/{report_id}/preview', 'ReportController@getReportPreview')->name('reportPreview');
        //マイページ
        Route::get('/mypage', 'MyPageController@index')->name('mypage');

        //============
        // その他
        //============
        //作業員登録処理
        Route::post('/vendorMember', 'VendorMemberController@store')->name('vendorMember.store');
        //作業員更新処理
        Route::put('/vendorMember/{user_id}', 'VendorMemberController@update')->name('vendorMember.update');
        //完了報告書更新処理
        Route::put('/report/{report_id}', 'ReportController@updateReport')->name('updateReport');
        //完了報告書提出処理
        Route::post('/report/{report_id}', 'ReportController@submitReport')->name('submitReport');
        //完了報告書PDFダウンロード処理
        Route::post('/report/{report_id}/pdf', 'ReportController@downloadReportPdf')->name('downloadReportPdf');
        //マイページ・更新処理
        Route::post('/mypage/update', 'MyPageController@update')->name('mypage.update');
        //問合せ担当者変更処理
        Route::post('/request/{request_id}/changeRequestHandler', 'RequestController@changeRequestHandler')->name('changeRequestHandler');
    });
});


//*************************************************************************************************************************
// 管理会社向け
//*************************************************************************************************************************
Route::namespace('Mc')->name('mc.')->prefix('mc')->group(function () {

    //ログイン認証関連
    Auth::routes([
        'register' => false,
        'reset'    => false,
        'verify'   => false
    ]);

    //ログイン認証後
    Route::middleware(['auth:guard_management_company_member', 'permission:management_company_member_permission','check.session.timeout'])->group(function () {
        //============
        // 画面
        //============
        //ダッシュボード画面
        Route::get('/', 'DashboardController@index')->name('dashboard');
        //問合せ一覧画面
        Route::get('/request', 'RequestController@index')->name('request');
        //問合せ一覧画面(ID指定)
        Route::get('/request/{request_id}/once', 'RequestController@index')->name('request.once');
        //ユーザー管理画面
        Route::get('/managementCompanyMember', 'ManagementCompanyMemberController@index')->name('managementCompanyMember');
        //完了報告一覧画面
        Route::get('/report', 'ReportController@getReportList')->name('reportList');
        //完了報告一覧画面
        Route::get('/report/{report_id}/once', 'ReportController@getReportList')->name('reportList.once');
        //完了報告書詳細画面
        Route::get('/report/{report_id}', 'ReportController@getReportDetail')->name('reportDetail');
        //入居者一覧画面
        Route::get('/resident', 'ResidentController@getResidentList')->name('residentList');

        //============
        // その他
        //============
        //AccessKeyファイルダウンロード処理
        Route::post('/getAccessKey', 'AccessKeyController@getAccessKey')->name('getAccessKey');
        //ユーザー登録処理
        Route::post('/managementCompanyMember', 'ManagementCompanyMemberController@store')->name('managementCompanyMember.store');
        //ユーザー更新処理
        Route::put('/managementCompanyMember/{user_id}', 'ManagementCompanyMemberController@update')->name('managementCompanyMember.update');
        //問合せ履歴 エクスポート
        Route::post('/request/export', 'RequestController@exportRequestCsv')->name('request.export');
        //完了報告書 承認処理
        Route::post('/report/{report_id}/approve', 'ReportController@approveReport')->name('approveReport');
        //完了報告書 差し戻し処理
        Route::post('/report/{report_id}/decline', 'ReportController@declineReport')->name('declineReport');
        //完了報告書PDFダウンロード処理
        Route::post('/report/{report_id}/pdf', 'ReportController@downloadReportPdf')->name('downloadReportPdf');
        //完了報告書ZIPファイルダウンロード処理
        Route::post('/report/{report_id}/zip', 'ReportController@downloadReportZip')->name('downloadReportZip');
    });
});


// パスワードリセット関連
Route::prefix('password_reset')->name('password_reset.')->group(function () {
    Route::prefix('email')->name('email.')->group(function () {
        // パスワードリセットメール送信フォームページ
        Route::get('/', 'Api\ForgotPasswordController@emailFormResetPassword')->name('form');
        // メール送信処理
        Route::post('/', 'Api\ForgotPasswordController@sendEmailResetPassword')->name('send');
        // メール送信完了ページ
        Route::get('/send_complete', 'Api\ForgotPasswordController@sendComplete')->name('send_complete');
    });
    // パスワード再設定ページ
    Route::get('/edit', 'Api\ForgotPasswordController@edit')->name('edit');
    // パスワード更新処理
    Route::post('/update', 'Api\ForgotPasswordController@update')->name('update');
    // パスワード更新終了ページ
    Route::get('/edited', 'Api\ForgotPasswordController@edited')->name('edited');
});


//*************************************************************************************************************************
// その他
//*************************************************************************************************************************
Route::name('other.')->group(function () {
    //============
    // 画面
    //============
    //本登録画面
    Route::get('/account/register', 'Mc\AccountController@index')->name('account');
    //本登録処理
    Route::post('/account/register', 'Mc\AccountController@register')->name('account.register');
});

relay-server/app/Http/Controllers/Vn/DashboardController.php
<?php

namespace App\Http\Controllers\Vn;

use App\Library\Cmn;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $webRequest)
    {
        $vendorId = $webRequest->session()->get('vendor_id');

        //管理会社別対応件数
        $chartByMc =
        \App\Models\Request::
        select(
            'mc.name',
            'r.management_company_id',
            \DB::raw('COUNT(*) as cnt'),
        )
        ->from('requests as r')
        ->join('management_companies as mc', function ($join) {
            $join->on('mc.management_company_id', 'r.management_company_id');
        })
        ->join('request_handle_users as rhu', function ($join) use ($vendorId) {
            $join->on('rhu.request_id', 'r.request_id')
            ->where('rhu.group_id', $vendorId);
        })
        ->groupBy([
            'mc.name',
            'r.management_company_id',
        ])
        ->get();

        //時間別問合せ数
        $selectChartByTimeZone =
        \App\Models\Request::
        select(
            \DB::raw('HOUR(r.created_at) as hour'),
            \DB::raw('COUNT(*) as cnt'),
        )
        ->from('requests as r')
        ->join('request_handle_users as rhu', function ($join) use ($vendorId) {
            $join->on('rhu.request_id', 'r.request_id')
            ->where('rhu.group_id', $vendorId);
        })
        ->groupBy('hour')
        ->get();
        $chartByTimeZone = array();
        for ($i = 0; $i < 24; $i++) {
            foreach ($selectChartByTimeZone as $cbtz) {
                if ($i == $cbtz->hour) {
                    array_push($chartByTimeZone, $cbtz->cnt);
                }
            }
            if (count($chartByTimeZone) === $i) {
                array_push($chartByTimeZone, 0);
            }
        }

        return view('vn.dashboard', [
            'chartByTimeZone' => $chartByTimeZone,
            'chartByMc' => $chartByMc,
        ]);
    }
}

relay-server/app/Http/Controllers/Vn/MyPageController.php
<?php

namespace App\Http\Controllers\Vn;

use App\Library\Cmn;
use App\Mail\CreateAccountVendorMemberNotification;
use App\Models\User;
use App\Models\Vendor;
use App\Models\VendorMember;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreVendor;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Http\Request;

class MyPageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $vendorId = $request->session()->get('vendor_id');
        $vendor = \App\Models\Vendor::find($vendorId);
        return view('vn/mypage', ['vendor' => $vendor]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //バリデーション
        $validatedData = $request->validate([
            'work_areas' => 'nullable',
            'work_time_from' => 'nullable|date_format:H:i',
            'work_time_to' => 'nullable|date_format:H:i',
            'work_weeks' => 'nullable',
            'work_items' => 'nullable',
        ]);

        try {
            DB::transaction(function () use ($request) {
                //変数
                $vendorId = $request->session()->get('vendor_id');
                $workAreas = $request->work_areas;
                $workTimeFrom = $request->work_time_from;
                $workTimeTo = $request->work_time_to;
                $workWeeks = $request->work_weeks;
                $workItems = $request->work_items;

                //更新
                $vendor = \App\Models\Vendor::find($vendorId);
                $vendor->work_areas = $workAreas;
                $vendor->work_time_from = $workTimeFrom;
                $vendor->work_time_to = $workTimeTo;
                $vendor->work_weeks = $workWeeks;
                $vendor->work_items = $workItems;
                $vendor->save();
            });

        } catch (\Exception $e) {
            \Log::error("システム例外が発生しました。".$e->getMessage());
            return redirect()->back()->withInput()->withErrors("システム例外が発生しました。".$e->getMessage());
        }

        return redirect(url()->previous())->with('my_status', '更新が完了しました。');
    }
}

relay-server/resources/views/vn/report/reportList.blade.php
@extends('layouts.vn.app')

@section('content')
@if ($s === 'submitted')
<div class="container-fluid" style="margin: 10px 0 -55px 0;padding: 0 59px;">
    <div class="row justify-content-center">
        <div class="alert alert-success col-md-12">完了報告書を提出しました。</div>
    </div>
</div>
@elseif ($s === 'updated')
<div class="container-fluid" style="margin: 10px 0 -55px 0;padding: 0 59px;">
    <div class="row justify-content-center">
        <div class="alert alert-success col-md-12">完了報告書を更新しました。</div>
    </div>
</div>
@endif
<ul class="nav nav-tabs pl-4">
  <li class="nav-item">
    <a class="nav-link @if ($section === config('const.Reports.DispSection.NOT_SUBMITTED')) active @endif" href="{{ route('vn.reportList', ['section' => config('const.Reports.DispSection.NOT_SUBMITTED')]) }}">未提出({{$not_submitted_cnt}})</a>
  </li>
  <li class="nav-item">
    <a class="nav-link @if ($section === config('const.Reports.DispSection.SUBMITTED')) active @endif" href="{{ route('vn.reportList', ['section' => config('const.Reports.DispSection.SUBMITTED')]) }}">提出済み</a>
  </li>
  <li class="nav-item">
    <a class="nav-link @if ($section === config('const.Reports.DispSection.REMAND')) active @endif" href="{{ route('vn.reportList', ['section' => config('const.Reports.DispSection.REMAND')]) }}">差し戻し({{$declined_cnt}})</a>
  </li>
</ul>
<div class="container-fluid px-5 mt-n3">
    <form method="GET" action="{{ route('vn.reportList') }}" onsubmit="buttonDisabled();">
        <input type="hidden" name="section" value="{{$section}}">
        <div class="row justify-content-center mt-4" id="searchConditions">
            <div class="col-md-4"><h6 class="searchCondLabel">物件名</h6></div>
            <div class="col-md-4"><h6 class="searchCondLabel">ステータス</h6></div>
            <div class="col-md-3"><h6 class="searchCondLabel">キーワード</h6></div>
            <div class="col-md-1"></div>
            <div class="col-md-4 search-form"><input type="text" name="property_name" class="form-control" value="{{ $conditions['property_name'] }}"></div>
            <div class="col-md-4">
                <select class="form-control" name="action_status">
                    <option value=""></option>
                    <option value="completed" @if($conditions['action_status'] === config('const.Reports.ActionStatus.COMPLETED')) selected @endif>対応完了</option>
                    <option value="incomplete" @if($conditions['action_status'] === config('const.Reports.ActionStatus.INCOMPLETE')) selected @endif>未完了引継ぎ</option>
                </select>
            </div>
            <div class="col-md-3 search-form"><input type="text" name="keyword" class="form-control" value="{{ $conditions['keyword'] }}"></div>
            <div class="col-md-1"></div>
            <div class="col-md-4"><h6 class="searchCondLabel">受付日</h6></div>
            <div class="col-md-4"><h6 class="searchCondLabel">工事日</h6></div>
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md"><input type="date" name="reception_date_from" class="form-control" value="{{ $conditions['reception_date_from'] }}"></div>
                    <div class="col-md-1 text-center font-size-22 font-weight-bold px-0">～</div>
                    <div class="col-md"><input type="date" name="reception_date_to" class="form-control" value="{{ $conditions['reception_date_to'] }}"></div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md"><input type="date" name="construction_date_from" class="form-control" value="{{ $conditions['construction_date_from'] }}"></div>
                    <div class="col-md-1 text-center font-size-22 font-weight-bold px-0">～</div>
                    <div class="col-md"><input type="date" name="construction_date_to" class="form-control" value="{{ $conditions['construction_date_to'] }}"></div>
                </div>
            </div>
            <div class="col-md-4">
                <button type="button" class="btn btn-clear mr-3">検索条件のクリア</button>
                <button type="submit" class="btn btn-search" style="width:160px;">検索</button>
            </div>
        </div>
    </form>
    <div class="row justify-content-center mt-4">
        <table class="table report-list">
            <tr>
                <th style="width:5%;"></th>
                <th style="width:11%;">管理会社</th>
                <th style="width:15%;">物件名</th>
                <th style="width:8%;">部屋番号</th>
                <th style="width:8%;">お客様名</th>
                <th style="width:9%;">@sortablelink('reception_date', '受付日')</th>
                <th style="width:10%;">ステータス</th>
                <th style="width:8%;">対応区分</th>
                <th style="width:9%;">@sortablelink('action_date', '工事日')</th>
                <th style="width:8%;">@sortablelink('construction_amount', '工事金額')</th>
                <th style="width:9%;">工事担当者名</th>
            </tr>
            @if ($reports->count() === 0)
                <tr><td colspan="11" class="text-center" style="cursor:default;font-size:18px;">検索結果がありませんでした</td></tr>
            @endif
            @foreach ($reports as $idx => $r)
                <tr data-href="{{url('/').route('vn.reportDetail', ['report_id' => $r->request_report_id], false)}}" data-toggle="modal" data-target="#modal">
                <td class="text-center">
                        @if ($r->image_path)
                            <img style="max-height:29px;max-width:38px;" src="{{ $r->image_path }}" title="{{ $r->request_report_id }}">
                        @else
                            <img style="max-height:29px;max-width:38px;" src="{{ asset('img/thmb-photo.svg') }}" title="{{ $r->request_report_id }}">
                        @endif
                    </td>
                    <td title="{{ $r->management_company_name }}">{{ $r->management_company_name }}</td>
                    <td title="{{ $r->property_name }}">{{ $r->property_name }}</td>
                    <td title="{{ $r->room_no }}">{{ $r->room_no }}</td>
                    <td title="{{ $r->resident_name }}">{{ $r->resident_name }}</td>
                    <td title="{{ Cmn::dateFormat($r->reception_date) }}">{{ Cmn::dateFormat($r->reception_date) }}</td>
                    <td>
                        @if ($r->action_status === config('const.Reports.ActionStatus.COMPLETED'))
                            <span class="reportListActionStatusComplete">対応完了</span>
                        @else
                            <span class="reportListActionStatusIncomplete">未完了引継ぎ</span>
                        @endif
                    </td>
                    <td>
                        <span class="reportListActionSection">
                            @if ($r->action_section === '1')
                                一次対応
                            @else
                                二次対応
                            @endif
                        </span>
                    </td>
                    <td title="{{ Cmn::dateFormat($r->action_date) }}">{{ Cmn::dateFormat($r->action_date) }}</td>
                    <td class="text-right" title="{{ number_format($r->construction_amount) }}">{{ number_format($r->construction_amount) }}</td>
                    <td title="{{ $r->user_name }}">{{ $r->user_name }}</td>
                </tr>
            @endforeach
        </table>
    </div>
    <div class="row justify-content-center">

        {{ $reports->appends(request()->query())->links() }}
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog">
<div class="modal-dialog modal-dialog-centered modal-dialog-fluid" role="document">
    <div class="modal-content p-0">
        <div id="modal-loading" style="width:100%;height:880px;">Loading...</div>
        <iframe id="iframe" src="" frameborder="0" scrolling="no" style="width:100%;height:880px;z-index:2000;"></iframe>
    </div>
  </div>
</div>

<script type="text/javascript">
    $('.btn-clear').on('click', function () {
        $('#searchConditions').find('input').val('');
        $('#searchConditions').find('option').attr("selected", false);
        $('#searchConditions').find('select').val('');
    });

    $("#modal").on("show.bs.modal", function(e) {
        $('#modal-loading').show();
        $('#iframe').hide();
        var link = $(e.relatedTarget);
        $('#iframe').attr('src', link.attr("data-href"));
    });

    $('#iframe').on('load', function() {
        $('#modal-loading').hide();
        $('#iframe').show();
    });

    function closeModal() {
        $('#modal').modal('hide');
    }
    function dispOverlay() {
        var overlay = '<div class="modal fade show" id="child-modal" tabindex="-1" aria-modal="true" style="display: block; padding-left: 17px;" onclick="childModalClose();"></div>';
        $('.modal-content').append(overlay);
    }
    function removeOverlay() {
        $('#child-modal').remove();
    }
    function childModalClose() {
        document.getElementById('iframe').contentWindow.closeModal();
    }
</script>
@endsection

relay-server/resources/views/vn/report/reportPdf.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Title -->
    <title>完了報告書</title>

    <style type="text/css">
        @font-face {
            font-family: ipag;
            font-style: normal;
            font-weight: normal;
            src: url('{{ storage_path('fonts/ipag.ttf') }}') format('truetype');
        }
        @font-face {
            font-family: ipag;
            font-style: bold;
            font-weight: bold;
            src: url('{{ storage_path('fonts/ipag.ttf') }}') format('truetype');
        }
        body {
            font-family: ipag !important;
            font-size: 38px;
            border: 5px solid #000;
            padding: 0;
        }
        .title {
            text-align: center;
            font-size: 50px;
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 20px;
        }
        .table {
            border-top: 1px #000 dotted;
            border-bottom: 1px #000 dotted;
            padding: 10px;
            width: 100%;
            margin-bottom: 10px;
            table-layout: fixed;
        }
        .td-title {
            width: 20%;
        }
        .description-table {
            border-bottom: 1px #000 dotted;
            padding: 0 10px 10px 10px;
            width: 100%;
            margin-bottom: 10px;
            table-layout: fixed;
            height: 540px;
        }
        .description-td {
            font-size: 22px;
            width: 100%;
            word-wrap: break-word;
            padding-right: 10px;
            vertical-align: top;
        }
        .other-table {
            padding:10px 0;
        }
    </style>
</style>
</head>

<body>
    <div class="title">
        @if (isset($preview))
            プレビュー
        @else
            完了報告書(@if ($report->report_status === config('const.Reports.Status.DRAFT'))未提出@elseif($report->report_status === config('const.Reports.Status.DECLINED'))差戻し@else提出済み@endif)
        @endif
    </div>
    <table class="table">
        <td class="td-title">受付日</td>
        <td>{{ Cmn::dateFormat($report->reception_date) }}</td>
    </table>
    <table class="table">
        <td class="td-title">物件名</td>
        <td>{{ $report->property_name }}</td>
        </table>
    <table class="table">
        <td class="td-title">部屋番号</td>
        <td>{{ $report->room_no }}号室</td>
    </table>
    <table class="table">
        <tr><td class="td-title">作業内容</td></tr>
    </table>
    <table class="description-table">
        <tr><td class="description-td">{!! nl2br($report->description) !!}</td></tr>
    </table>
    <table class="table">
        <td class="td-title">工事日</td>
        <td>{{ Cmn::dateFormat($report->action_date) }}</td>
    </table>
    <table class="table">
        <td class="td-title">対応時間</td>
        <td>{{ substr($report->starting_time, 0, 5) }} ～ {{ substr($report->ending_time, 0, 5) }}</td>
    </table>
    <table class="table">
        <td class="td-title">工事金額</td>
        <td>{{ number_format($report->construction_amount) }}円</td>
    </table>
    <table class="other-table" style="border-top:1px solid #000;width:100%;margin:0;">
        <tr>
            <td style="width:30%;vertical-align:middle;">
                @if($report->action_section === '1')
                    <img style="margin: 0 5px;" src="{{ asset('img/icon-checkbox.png') }}">一次対応
                @else
                    <img style="margin: 0 5px;" src="{{ asset('img/icon-checkbox-none.png') }}">一次対応
                @endif
            </td>
            <td rowspan="2">上記の内容で作業を実施しました。</td>
        </tr>
        <tr>
            <td style="vertical-align:middle;">
                @if($report->action_section === '2')
                    <img style="margin: 0 5px;" src="{{ asset('img/icon-checkbox.png') }}">二次対応
                @else
                    <img style="margin: 0 5px;" src="{{ asset('img/icon-checkbox-none.png') }}">二次対応
                @endif
            </td>
        </tr>
    </table>
    <table class="other-table" style="border-top:1px solid #000;border-bottom:1px solid #000;width:100%;margin:0;">
        <tr>
            <td style="width:30%;">
                @if($report->action_status === config('const.Reports.ActionStatus.INCOMPLETE'))
                    <img style="margin: 0 5px;" src="{{ asset('img/icon-checkbox.png') }}">未完了引継ぎ
                @else
                    <img style="margin: 0 5px;" src="{{ asset('img/icon-checkbox-none.png') }}">未完了引継ぎ
                @endif
            </td>
            <td>お客様名</td>
            <td>{{ $report->resident_name }}</td>
        </tr>
        <tr>
            <td>
                @if($report->action_status === config('const.Reports.ActionStatus.INCOMPLETE'))
                    <img style="margin: 0 5px;" src="{{ asset('img/icon-checkbox-none.png') }}">工事完了
                @else
                    <img style="margin: 0 5px;" src="{{ asset('img/icon-checkbox.png') }}">工事完了
                @endif
            </td>
            <td>作業担当者名</td>
            <td>{{ $report->user_name }}</td>
        </tr>
    </table>
</body>
</html>